#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyLibraryApp.Resource", IsApplication=true)]

namespace MyLibraryApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int accountsButton = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int cancelButton = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int deleteButton = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int firstNameInput = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int lastNameInput = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int learnMoreButton = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int librariesButton = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int libraryInput = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int libraryTypes = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int listView = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int nameInput = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int newButton = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int saveButton = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int uriInput = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int usersButton = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Accounts = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddAccount = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditLibrary = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditUser = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Libraries = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Users = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int add_library = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int add_user = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int edit_library = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int edit_user = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
